steps:
  - name: node:12
    entrypoint: yarn
    args:
      - install
      - --production
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --plaintext-file=secrets.json
      - --ciphertext-file=secrets.json.enc
      - --location=global
      - --keyring=secrets
      - --key=password
  - name: node:12
    entrypoint: yarn
    args:
      - build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/loguxio
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/loguxio
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - beta
      - run
      - deploy
      - loguxio
      - --image=gcr.io/logux-255417/loguxio
      - --region=us-east1
      - --platform=managed
  - name: node:12
    entrypoint: ./scripts/update-cdn
images:
  - gcr.io/$PROJECT_ID/loguxio
