name: Deploy to GCR

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Install Node.js
        uses: actions/setup-node@master
        with:
          node-version: '>=13.2'
      - name: Install dependencies
        run: yarn install --production
      - name: Build and test
        run: yarn test
