name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Install Node.js
        uses: actions/setup-node@master
        with:
          node-version: '>=13.2'
      - name: Get Yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-production-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-production-
      - name: Install dependencies
        run: yarn install --production
      - name: Build static files
        run: yarn build
        env:
          CI: 1
          GITTER_ROOM_ID: ${{ secrets.GITTER_ROOM_ID }}
          GITTER_TOKEN: ${{ secrets.GITTER_TOKEN }}
      - name: Build Docker image
        run: docker build -t gcr.io/logux-255417/loguxio .
